logging:
  receivers:
    syslog:
      type: files
      include_paths:
        - /var/log/messages
        - /var/log/syslog
  processors:
    parse_json:
      type: parse_json
      field: message
      time_key: "@timestamp"
      time_format: "%Y-%m-%dT%H:%M:%S.%L%z"
  service:
    pipelines:
      default_pipeline:
        receivers: [syslog]
        processors: [parse_json]
